import type { Company, Password, Vault } from "./types"

export const companies: Company[] = [
  { id: "1", name: "Acme Corp" },
  { id: "2", name: "Startup Inc" },
  { id: "3", name: "Tech Solutions" },
  { id: "3", name: "Tech Solutions" },
  { id: "3", name: "Tech Solutions" },
  { id: "3", name: "Tech Solutions" },
  { id: "3", name: "Tech Solutions" },
  { id: "3", name: "Tech Solutions" },
  { id: "3", name: "Tech Solutions" },
  { id: "3", name: "Tech Solutions" },
  { id: "3", name: "Tech Solutions" },
  { id: "3", name: "Tech Solutions" },
]

export const vaults: Vault[] = [
  {
    id: "marketing",
    name: "Marketing",
    description: "Social media accounts",
    icon: "megaphone",
    iconBg: "bg-blue-100",
    accessLevel: "Read",
  },
  {
    id: "sales",
    name: "Sales",
    description: "Sales-related passwords",
    icon: "bar-chart",
    iconBg: "bg-orange-100",
    accessLevel: "Admin",
  },
  {
    id: "engineering",
    name: "Engineering",
    description: "Developer tools",
    icon: "blocks",
    iconBg: "bg-blue-100",
    accessLevel: "Read",
  },
]

export const passwords: Password[] = [
  {
    id: "aws",
    vaultId: "engineering",
    name: "AWS Console",
    description: "AWS management",
    icon: "triangle",
    iconBg: "bg-green-100",
    url: "aws.amazon.com",
    username: "admin@acmecorp.com",
    password: "securePassword123!",
    notes: "Main AWS account for infrastructure",
    addedAt: "2023-05-15T10:30:00Z",
    updatedAt: "2023-11-22T14:45:00Z",
    accessIndicator: "dot",
  },
  {
    id: "github",
    vaultId: "engineering",
    name: "GitHub",
    description: "Source code hosting",
    icon: "github",
    iconBg: "bg-gray-200",
    url: "github.com",
    username: "acmecorp",
    password: "githubSecure456!",
    notes: "Organization account for all repositories",
    addedAt: "2023-04-10T09:15:00Z",
    updatedAt: "2023-10-05T11:20:00Z",
    accessIndicator: "SV",
  },
  {
    id: "docker",
    vaultId: "engineering",
    name: "Docker Hub",
    description: "Container registry",
    icon: "docker",
    iconBg: "bg-blue-100",
    url: "hub.docker.com",
    username: "acmecorp",
    password: "dockerPass789!",
    notes: "For storing and distributing container images",
    addedAt: "2023-06-20T13:40:00Z",
    updatedAt: "2023-12-01T16:30:00Z",
  },
  {
    id: "facebook",
    vaultId: "marketing",
    name: "Facebook",
    description: "Company page",
    icon: "facebook",
    iconBg: "bg-blue-500",
    url: "facebook.com",
    username: "marketing@acmecorp.com",
    password: "fbMarketingPass!",
    notes: "Main company page credentials",
    addedAt: "2023-03-12T08:20:00Z",
    updatedAt: "2023-09-18T15:10:00Z",
  },
  {
    id: "instagram",
    vaultId: "marketing",
    name: "Instagram",
    description: "Company profile",
    icon: "instagram",
    iconBg: "bg-pink-100",
    url: "instagram.com",
    username: "acmecorp_official",
    password: "instaSecure2023!",
    notes: "Brand account for product showcases",
    addedAt: "2023-02-25T11:45:00Z",
    updatedAt: "2023-08-30T09:55:00Z",
  },
  {
    id: "salesforce",
    vaultId: "sales",
    name: "Salesforce",
    description: "CRM platform",
    icon: "cloud",
    iconBg: "bg-blue-200",
    url: "salesforce.com",
    username: "sales.admin@acmecorp.com",
    password: "sfAdmin2023!",
    notes: "Main admin account for Salesforce",
    addedAt: "2023-01-15T14:30:00Z",
    updatedAt: "2023-07-22T10:15:00Z",
  },
  {
    id: "hubspot",
    vaultId: "sales",
    name: "HubSpot",
    description: "Marketing automation",
    icon: "activity",
    iconBg: "bg-orange-200",
    url: "hubspot.com",
    username: "marketing@acmecorp.com",
    password: "hubSpotPass123!",
    notes: "For email campaigns and lead tracking",
    addedAt: "2023-04-05T16:20:00Z",
    updatedAt: "2023-10-12T13:40:00Z",
  },
]
